baseURL = '/'
languageCode = 'en-us'
title = 'Saddleback Computer Science Site'
theme = 'PaperMod'

buildDrafts = true

[params]
  ShowReadingTime = true
  ShowWordCount = true

# Remove 'posts' path in page urls
[permalinks]
  posts = "/:title"